collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9980129
  brandStrength: 0.7517761
  rhythmicContrast: 0.7636464
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.9383623
typography_spectrum: 1
layout_spectrum: 0.7885305
name: HG Cabinet Blog
