collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.7598566
color:
  saturation: 0.469534
  brandStrength: 0.5322581
  lightness: 0.08781362
  brandColors:
    - '#FFFFFF'
    - '#999999'
    - '#290A01'
    - '#624A3A'
    - '#47AED6'
  rhythmicContrast: 0.9390681
layout_spectrum: 1
name: HG Cabinet Blog
